project_id = "ybtrzqzliepknpzqdajx"

[functions.fetch-site-banner]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.create-engineer]
verify_jwt = false

[functions.update-engineer]
verify_jwt = false

[functions.delete-engineer]
verify_jwt = false

[functions.list-engineers]
verify_jwt = false

[functions.create-operator-account]
verify_jwt = false

[functions.reset-operator-password]
verify_jwt = false
