// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-work-orders.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_work_orders_default = defineTool({
  name: "list_work_orders",
  title: "List work orders",
  description: "List recent maintenance work orders visible to the signed-in user. Optionally filter by status or priority.",
  inputSchema: {
    status: z.enum(["OPEN", "IN_PROGRESS", "PAUSED", "FINISHED", "CANCELLED", "PENDING", "COMPLETED"]).optional().describe("Filter by work order status."),
    priority: z.enum(["low", "medium", "high", "critical"]).optional().describe("Filter by priority."),
    limit: z.number().int().min(1).max(100).default(25).describe("Max rows to return (1\u2013100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, priority, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("work_orders").select(
      "id, wo_number, description, status, priority, machine, requester_name, engineer_name, created_at, started_at, finished_at"
    ).order("created_at", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    if (priority) query = query.eq("priority", priority);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-work-order.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_work_order_default = defineTool2({
  name: "get_work_order",
  title: "Get work order",
  description: "Fetch a single work order by its UUID or numeric wo_number.",
  inputSchema: {
    id: z2.string().optional().describe("Work order UUID."),
    wo_number: z2.number().int().optional().describe("Numeric wo_number (e.g. 1234).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, wo_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!id && !wo_number) {
      return { content: [{ type: "text", text: "Provide id or wo_number." }], isError: true };
    }
    let query = supabaseForUser2(ctx).from("work_orders").select("*").limit(1);
    if (id) query = query.eq("id", id);
    else if (wo_number) query = query.eq("wo_number", wo_number);
    const { data, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { row: data }
    };
  }
});

// src/lib/mcp/tools/list-machines.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_machines_default = defineTool3({
  name: "list_machines",
  title: "List machines",
  description: "List equipment/machines in the plant, optionally filtered by production line.",
  inputSchema: {
    line_id: z3.string().optional().describe("Optional production line UUID to filter by."),
    limit: z3.number().int().min(1).max(200).default(50).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ line_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser3(ctx).from("machines").select("id, name, line_id, status, updated_at").order("name", { ascending: true }).limit(limit);
    if (line_id) query = query.eq("line_id", line_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-lines.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_lines_default = defineTool4({
  name: "list_lines",
  title: "List production lines",
  description: "List all production lines the signed-in user can see.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("production_lines").select("id, name").order("name", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-work-order.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_work_order_default = defineTool5({
  name: "create_work_order",
  title: "Create work order",
  description: "Create a new maintenance work order as the signed-in user. Requires a description and requester name.",
  inputSchema: {
    description: z4.string().trim().min(3).describe("What is broken or needs maintenance."),
    requester_name: z4.string().trim().min(1).describe("Name of the person requesting."),
    priority: z4.enum(["low", "medium", "high", "critical"]).default("medium").describe("Priority; defaults to medium."),
    machine: z4.string().trim().optional().describe("Machine name (free text)."),
    line_id: z4.string().optional().describe("Production line UUID, if applicable."),
    notes: z4.string().optional().describe("Extra context or notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("work_orders").insert({
      description: input.description,
      requester_name: input.requester_name,
      priority: input.priority,
      machine: input.machine ?? null,
      line_id: input.line_id ?? null,
      notes: input.notes ?? null,
      operator_id: ctx.getUserId()
    }).select("id, wo_number, status, priority, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created WO #${data.wo_number}` }],
      structuredContent: { row: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ybtrzqzliepknpzqdajx";
var mcp_default = defineMcp({
  name: "an-maintenance-mcp",
  title: "AN Maintenance MCP",
  version: "0.1.0",
  instructions: "Tools for the AN Maintenance system. Use `list_work_orders` / `get_work_order` to inspect maintenance activity, `list_machines` / `list_lines` to browse assets, and `create_work_order` to log a new maintenance request as the signed-in user. All calls run under the user's row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_work_orders_default, get_work_order_default, list_machines_default, list_lines_default, create_work_order_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
