name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do codigo
      uses: actions/checkout@v4

    - name: Configurar o Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Instalar Dependencias
      run: bun install --frozen-lockfile

    - name: Executar os Testes
      run: bun run test
